version : "3"
services : 
  db:
    image: postgres
    container_name: coffee_db
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: test
    volumes:
      - pgdata:/var/lib/lib/postgresql/data

  web:
    image: node:14
    working_dir: /home/node/app/
    command: npm run docker-dev
    container_name: nodejs
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes: 
      - .:/home/node/app

volumes:
  pgdata:
